# Generated by Django 4.1.4 on 2023-01-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_reply_comment'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='reply',
            order_with_respect_to='comment',
        ),
    ]
