# Generated by Django 4.1.4 on 2023-01-11 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_reply_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='reply',
            order_with_respect_to='created_at',
        ),
    ]
