# Generated by Django 4.1.4 on 2023-01-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_reply_order_with_respect_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterOrderWithRespectTo(
            name='reply',
            order_with_respect_to='comment',
        ),
    ]
